package au.com.noojee.acceloapi.entities.meta;

import au.com.noojee.acceloapi.entities.AccountDetails;
/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.generator.FieldMetaDataGenerator
 *
 * The generator use @AcceloField annotations to determine what fields to include in the Meta data.
 *
 *          DO NOT MODIFY 
 *
 */
import au.com.noojee.acceloapi.entities.meta.fieldTypes.FilterField;


public class AccountDetails_ 
{

	public static FilterField<AccountDetails, Integer> id = new FilterField<>("id"); 
	public static FilterField<AccountDetails, String> title = new FilterField<>("title"); 

}
