package au.com.noojee.acceloapi.entities.meta;

import java.time.LocalDate;

/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.meta.FieldMetaDataGenerator
 *
 *          DO NOT MODIFY 
 *
 */
import au.com.noojee.acceloapi.entities.Affiliation;


public class Affiliation_ 
{

	public static FilterField<Affiliation, String> mobile = new FilterField<>("mobile"); 
	public static FilterField<Affiliation, Integer> postal_address = new FilterField<>("postal_address"); 
	public static FilterField<Affiliation, Integer> physical_address = new FilterField<>("physical_address"); 
	public static FilterField<Affiliation, String> email = new FilterField<>("email"); 
	public static FilterField<Affiliation, Integer> id = new FilterField<>("id"); 
	public static FilterField<Affiliation, Integer> company = new FilterField<>("company"); 
	public static FilterField<Affiliation, String> phone = new FilterField<>("phone"); 
	public static FilterField<Affiliation, LocalDate> date_modified = new FilterField<>("date_modified"); 
	public static FilterField<Affiliation, Integer> contact = new FilterField<>("contact"); 
	public static FilterField<Affiliation, String> standing = new FilterField<>("standing"); 

}
