package au.com.noojee.acceloapi.entities.meta;

import java.time.LocalDate;

/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.meta.FieldMetaDataGenerator
 *
 *          DO NOT MODIFY 
 *
 */
import au.com.noojee.acceloapi.entities.Company;


public class Company_ 
{

	public static FilterField<Company, Integer> default_affiliation = new FilterField<>("default_affiliation"); 
	public static FilterField<Company, String> website = new FilterField<>("website"); 
	public static FilterField<Company, Integer> postal_address = new FilterField<>("postal_address"); 
	public static FilterField<Company, LocalDate> date_created = new FilterField<>("date_created"); 
	public static FilterField<Company, Integer> id = new FilterField<>("id"); 
	public static FilterField<Company, String> name = new FilterField<>("name"); 
	public static FilterField<Company, Integer> status = new FilterField<>("status"); 
	public static FilterField<Company, String> fax = new FilterField<>("fax"); 
	public static FilterField<Company, String> standing = new FilterField<>("standing"); 
	public static FilterField<Company, String> phone = new FilterField<>("phone"); 
	public static FilterField<Company, LocalDate> date_modified = new FilterField<>("date_modified"); 

}
