package au.com.noojee.acceloapi.entities.meta;

/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.meta.FieldMetaDataGenerator
 *
 * The generator use @AcceloField annotations to determine what fields to include in the Meta data.
 *
 *          DO NOT MODIFY 
 *
 */
import java.time.LocalDate;
import au.com.noojee.acceloapi.entities.Company;


public class Company_ 
{

	public static FilterField<Company, Integer> default_affiliation = new FilterField<>("default_affiliation"); 
	public static FilterField<Company, Integer> manager_id = new FilterField<>("manager_id"); 
	public static FilterField<Company, Integer> postal_address = new FilterField<>("postal_address"); 
	public static FilterField<Company, LocalDate> date_created = new FilterField<>("date_created"); 
	public static FilterField<Company, Integer> id = new FilterField<>("id"); 
	public static FilterField<Company, Integer> status = new FilterField<>("status"); 
	public static FilterField<Company, String> standing = new FilterField<>("standing"); 
	public static FilterField<Company, String> contact_number = new FilterField<>("contact_number"); 
	public static FilterField<Company, LocalDate> date_modified = new FilterField<>("date_modified"); 

}
