package au.com.noojee.acceloapi.entities.meta;

/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.generator.FieldMetaDataGenerator
 *
 * The generator use @AcceloField annotations to determine what fields to include in the Meta data.
 *
 *          DO NOT MODIFY 
 *
 */
import au.com.noojee.acceloapi.entities.meta.fieldTypes.FilterField;
import au.com.noojee.acceloapi.entities.Contact;
import java.time.LocalDateTime;


public class Contact_ 
{

	public static FilterField<Contact, String> affiliation = new FilterField<>("affiliation"); 
	public static FilterField<Contact, String> contact_number = new FilterField<>("contact_number"); 
	public static FilterField<Contact,LocalDateTime>date_created = new FilterField<>("date_created"); 
	public static FilterField<Contact,LocalDateTime>date_modified = new FilterField<>("date_modified"); 
	public static FilterField<Contact, String> email = new FilterField<>("email"); 
	public static FilterField<Contact, Integer> id = new FilterField<>("id"); 
	public static FilterField<Contact, String> standing = new FilterField<>("standing"); 
	public static FilterField<Contact, Integer> status = new FilterField<>("status"); 
	public static FilterField<Contact, String> title = new FilterField<>("title"); 
	public static FilterField<Contact, String> username = new FilterField<>("username"); 

}
