package au.com.noojee.acceloapi.entities.meta;

import java.time.LocalDate;

/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.meta.FieldMetaDataGenerator
 *
 *          DO NOT MODIFY 
 *
 */
import au.com.noojee.acceloapi.entities.Contact;


public class Contact_ 
{

	public static FilterField<Contact, String> surname = new FilterField<>("surname"); 
	public static FilterField<Contact, String> email = new FilterField<>("email"); 
	public static FilterField<Contact, Integer> id = new FilterField<>("id"); 
	public static FilterField<Contact, String> firstname = new FilterField<>("firstname"); 
	public static FilterField<Contact, String> title = new FilterField<>("title"); 
	public static FilterField<Contact, LocalDate> date_modified = new FilterField<>("date_modified"); 
	public static FilterField<Contact, String> standing = new FilterField<>("standing"); 
	public static FilterField<Contact, String> username = new FilterField<>("username"); 
	public static FilterField<Contact, Integer> status = new FilterField<>("status"); 
	public static FilterField<Contact, LocalDate> date_created = new FilterField<>("date_created"); 

}
