package au.com.noojee.acceloapi.entities.meta;

import au.com.noojee.acceloapi.entities.CustomField;
/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.generator.FieldMetaDataGenerator
 *
 * The generator use @AcceloField annotations to determine what fields to include in the Meta data.
 *
 *          DO NOT MODIFY 
 *
 */
import au.com.noojee.acceloapi.entities.meta.fieldTypes.FilterField;


public class CustomField_ 
{

	public static FilterField<CustomField, Integer> id = new FilterField<>("id"); 

}
