package au.com.noojee.acceloapi.entities.meta;

import java.time.LocalDate;

/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.meta.FieldMetaDataGenerator
 *
 *          DO NOT MODIFY 
 *
 */
import au.com.noojee.acceloapi.entities.Invoice;


public class Invoice_ 
{

	public static FilterField<Invoice, LocalDate> date_raised = new FilterField<>("date_raised"); 
	public static FilterField<Invoice, LocalDate> date_due = new FilterField<>("date_due"); 
	public static FilterField<Invoice, Integer> id = new FilterField<>("id"); 
	public static FilterField<Invoice, Integer> invoice_number = new FilterField<>("invoice_number"); 
	public static FilterField<Invoice, LocalDate> date_modified = new FilterField<>("date_modified"); 

}
