package au.com.noojee.acceloapi.entities.meta;

import java.time.LocalDate;

import au.com.noojee.acceloapi.entities.Request;
/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.generator.FieldMetaDataGenerator
 *
 * The generator use @AcceloField annotations to determine what fields to include in the Meta data.
 *
 *          DO NOT MODIFY 
 *
 */
import au.com.noojee.acceloapi.entities.meta.fieldTypes.FilterField;


public class Request_ 
{

	public static FilterField<Request, Integer> affiliation_id = new FilterField<>("affiliation_id"); 
	public static FilterField<Request, Integer> claimer_id = new FilterField<>("claimer_id"); 
	public static FilterField<Request, LocalDate> date_created = new FilterField<>("date_created"); 
	public static FilterField<Request, Integer> id = new FilterField<>("id"); 
	public static FilterField<Request, Integer> lead_id = new FilterField<>("lead_id"); 
	public static FilterField<Request, Integer> priority_id = new FilterField<>("priority_id"); 
	public static FilterField<Request, String> standing = new FilterField<>("standing"); 
	public static FilterField<Request, Integer> type_id = new FilterField<>("type_id"); 

}
