package au.com.noojee.acceloapi.entities.meta;

/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.meta.FieldMetaDataGenerator
 *
 *          DO NOT MODIFY 
 *
 */
import au.com.noojee.acceloapi.entities.Staff;


public class Staff_ 
{

	public static FilterField<Staff, Integer> id = new FilterField<>("id"); 
	public static FilterField<Staff, String> username = new FilterField<>("username"); 
	public static FilterField<Staff, String> email = new FilterField<>("email"); 

}
