package au.com.noojee.acceloapi.entities.meta;

/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.meta.FieldMetaDataGenerator
 *
 * The generator use @AcceloField annotations to determine what fields to include in the Meta data.
 *
 *          DO NOT MODIFY 
 *
 */
import au.com.noojee.acceloapi.entities.Staff;
import au.com.noojee.acceloapi.entities.generator.FilterField;


public class Staff_ 
{

	public static FilterField<Staff, String> email = new FilterField<>("email"); 
	public static FilterField<Staff, Integer> id = new FilterField<>("id"); 
	public static FilterField<Staff, String> standing = new FilterField<>("standing"); 
	public static FilterField<Staff, String> username = new FilterField<>("username"); 

}
