package au.com.noojee.acceloapi.entities.meta;

import java.time.LocalDate;

/** 
 *
 *          DO NOT MODIFY 
 *
 * This code is generated by au.com.noojee.acceloapi.entities.meta.FieldMetaDataGenerator
 *
 * The generator use @AcceloField annotations to determine what fields to include in the Meta data.
 *
 *          DO NOT MODIFY 
 *
 */
import au.com.noojee.acceloapi.entities.TimeAllocation;


public class TimeAllocation_ 
{

	public static FilterField<TimeAllocation, LocalDate> date_created = new FilterField<>("date_created"); 
	public static FilterField<TimeAllocation, LocalDate> date_locked = new FilterField<>("date_locked"); 
	public static FilterField<TimeAllocation, Integer> id = new FilterField<>("id"); 
	public static FilterField<TimeAllocation, String> standing = new FilterField<>("standing"); 

}
